<?php
header('Content-Type: application/json');

echo json_encode([
  ["title" => "Math Revision #1", "content" => "Review algebra and trigonometry before next week's quiz. (Round 1)"],
  ["title" => "History Exam #1", "content" => "Study World War II topics for the upcoming history exam. (Round 1)"],
  ["title" => "Group Meeting #1", "content" => "Don't forget the group project meeting on Tuesday at 3 PM. (Round 1)"],
  ["title" => "Submit Assignment #1", "content" => "Upload your physics assignment by Friday evening. (Round 1)"],
  ["title" => "Presentation Practice #1", "content" => "Rehearse your slides for Friday's presentation. (Round 1)"],
  ["title" => "Read a Chapter #1", "content" => "Finish reading Chapter 5 of your psychology textbook. (Round 1)"],
  ["title" => "Quiz Reminder #1", "content" => "Prepare for the biology quiz on photosynthesis. (Round 1)"],
  ["title" => "Essay Planning #1", "content" => "Outline your essay on climate change today. (Round 1)"],
  ["title" => "Flashcard Review #1", "content" => "Go through the flashcards made for chemistry. (Round 1)"],
  ["title" => "Organize Desk #1", "content" => "Clean and arrange your study space for better focus. (Round 1)"],
  ["title" => "Focus Session #1", "content" => "Try a 25-minute Pomodoro session with full concentration. (Round 1)"],
  ["title" => "Take a Break #1", "content" => "Stretch, hydrate and relax for 10 minutes. (Round 1)"],
  ["title" => "Daily Plan #1", "content" => "Make a to-do list for today’s tasks. (Round 1)"],
  ["title" => "Weekly Goals #1", "content" => "List 3 goals to complete this week. (Round 1)"],
  ["title" => "Digital Declutter #1", "content" => "Sort out your computer desktop files. (Round 1)"],
  ["title" => "Motivation Boost #1", "content" => "Remember: small progress is still progress. (Round 1)"],
  ["title" => "Catch Up #1", "content" => "Revisit lessons or materials you missed. (Round 1)"],
  ["title" => "Practice Questions #1", "content" => "Solve 5 sample problems from your workbook. (Round 1)"],
  ["title" => "Time to Reflect #1", "content" => "Write 3 sentences about what you learned today. (Round 1)"],
  ["title" => "Stay Consistent #1", "content" => "Even 10 minutes a day helps—keep showing up! (Round 1)"],
  ["title" => "Math Revision #2", "content" => "Review algebra and trigonometry before next week's quiz. (Round 2)"],
  ["title" => "History Exam #2", "content" => "Study World War II topics for the upcoming history exam. (Round 2)"],
  ["title" => "Group Meeting #2", "content" => "Don't forget the group project meeting on Tuesday at 3 PM. (Round 2)"],
  ["title" => "Submit Assignment #2", "content" => "Upload your physics assignment by Friday evening. (Round 2)"],
  ["title" => "Presentation Practice #2", "content" => "Rehearse your slides for Friday's presentation. (Round 2)"],
  ["title" => "Read a Chapter #2", "content" => "Finish reading Chapter 5 of your psychology textbook. (Round 2)"],
  ["title" => "Quiz Reminder #2", "content" => "Prepare for the biology quiz on photosynthesis. (Round 2)"],
  ["title" => "Essay Planning #2", "content" => "Outline your essay on climate change today. (Round 2)"],
  ["title" => "Flashcard Review #2", "content" => "Go through the flashcards made for chemistry. (Round 2)"],
  ["title" => "Organize Desk #2", "content" => "Clean and arrange your study space for better focus. (Round 2)"],
  ["title" => "Focus Session #2", "content" => "Try a 25-minute Pomodoro session with full concentration. (Round 2)"],
  ["title" => "Take a Break #2", "content" => "Stretch, hydrate and relax for 10 minutes. (Round 2)"],
  ["title" => "Daily Plan #2", "content" => "Make a to-do list for today’s tasks. (Round 2)"],
  ["title" => "Weekly Goals #2", "content" => "List 3 goals to complete this week. (Round 2)"],
  ["title" => "Digital Declutter #2", "content" => "Sort out your computer desktop files. (Round 2)"],
  ["title" => "Motivation Boost #2", "content" => "Remember: small progress is still progress. (Round 2)"],
  ["title" => "Catch Up #2", "content" => "Revisit lessons or materials you missed. (Round 2)"],
  ["title" => "Practice Questions #2", "content" => "Solve 5 sample problems from your workbook. (Round 2)"],
  ["title" => "Time to Reflect #2", "content" => "Write 3 sentences about what you learned today. (Round 2)"],
  ["title" => "Stay Consistent #2", "content" => "Even 10 minutes a day helps—keep showing up! (Round 2)"],
  ["title" => "Math Revision #3", "content" => "Review algebra and trigonometry before next week's quiz. (Round 3)"],
  ["title" => "History Exam #3", "content" => "Study World War II topics for the upcoming history exam. (Round 3)"],
  ["title" => "Group Meeting #3", "content" => "Don't forget the group project meeting on Tuesday at 3 PM. (Round 3)"],
  ["title" => "Submit Assignment #3", "content" => "Upload your physics assignment by Friday evening. (Round 3)"],
  ["title" => "Presentation Practice #3", "content" => "Rehearse your slides for Friday's presentation. (Round 3)"],
  ["title" => "Read a Chapter #3", "content" => "Finish reading Chapter 5 of your psychology textbook. (Round 3)"],
  ["title" => "Quiz Reminder #3", "content" => "Prepare for the biology quiz on photosynthesis. (Round 3)"],
  ["title" => "Essay Planning #3", "content" => "Outline your essay on climate change today. (Round 3)"],
  ["title" => "Flashcard Review #3", "content" => "Go through the flashcards made for chemistry. (Round 3)"],
  ["title" => "Organize Desk #3", "content" => "Clean and arrange your study space for better focus. (Round 3)"],
  ["title" => "Focus Session #3", "content" => "Try a 25-minute Pomodoro session with full concentration. (Round 3)"],
  ["title" => "Take a Break #3", "content" => "Stretch, hydrate and relax for 10 minutes. (Round 3)"],
  ["title" => "Daily Plan #3", "content" => "Make a to-do list for today’s tasks. (Round 3)"],
  ["title" => "Weekly Goals #3", "content" => "List 3 goals to complete this week. (Round 3)"],
  ["title" => "Digital Declutter #3", "content" => "Sort out your computer desktop files. (Round 3)"],
  ["title" => "Motivation Boost #3", "content" => "Remember: small progress is still progress. (Round 3)"],
  ["title" => "Catch Up #3", "content" => "Revisit lessons or materials you missed. (Round 3)"],
  ["title" => "Practice Questions #3", "content" => "Solve 5 sample problems from your workbook. (Round 3)"],
  ["title" => "Time to Reflect #3", "content" => "Write 3 sentences about what you learned today. (Round 3)"],
  ["title" => "Stay Consistent #3", "content" => "Even 10 minutes a day helps—keep showing up! (Round 3)"],
  ["title" => "Math Revision #4", "content" => "Review algebra and trigonometry before next week's quiz. (Round 4)"],
  ["title" => "History Exam #4", "content" => "Study World War II topics for the upcoming history exam. (Round 4)"],
  ["title" => "Group Meeting #4", "content" => "Don't forget the group project meeting on Tuesday at 3 PM. (Round 4)"],
  ["title" => "Submit Assignment #4", "content" => "Upload your physics assignment by Friday evening. (Round 4)"],
  ["title" => "Presentation Practice #4", "content" => "Rehearse your slides for Friday's presentation. (Round 4)"],
  ["title" => "Read a Chapter #4", "content" => "Finish reading Chapter 5 of your psychology textbook. (Round 4)"],
  ["title" => "Quiz Reminder #4", "content" => "Prepare for the biology quiz on photosynthesis. (Round 4)"],
  ["title" => "Essay Planning #4", "content" => "Outline your essay on climate change today. (Round 4)"],
  ["title" => "Flashcard Review #4", "content" => "Go through the flashcards made for chemistry. (Round 4)"],
  ["title" => "Organize Desk #4", "content" => "Clean and arrange your study space for better focus. (Round 4)"],
  ["title" => "Focus Session #4", "content" => "Try a 25-minute Pomodoro session with full concentration. (Round 4)"],
  ["title" => "Take a Break #4", "content" => "Stretch, hydrate and relax for 10 minutes. (Round 4)"],
  ["title" => "Daily Plan #4", "content" => "Make a to-do list for today’s tasks. (Round 4)"],
  ["title" => "Weekly Goals #4", "content" => "List 3 goals to complete this week. (Round 4)"],
  ["title" => "Digital Declutter #4", "content" => "Sort out your computer desktop files. (Round 4)"],
  ["title" => "Motivation Boost #4", "content" => "Remember: small progress is still progress. (Round 4)"],
  ["title" => "Catch Up #4", "content" => "Revisit lessons or materials you missed. (Round 4)"],
  ["title" => "Practice Questions #4", "content" => "Solve 5 sample problems from your workbook. (Round 4)"],
  ["title" => "Time to Reflect #4", "content" => "Write 3 sentences about what you learned today. (Round 4)"],
  ["title" => "Stay Consistent #4", "content" => "Even 10 minutes a day helps—keep showing up! (Round 4)"],
  ["title" => "Math Revision #5", "content" => "Review algebra and trigonometry before next week's quiz. (Round 5)"],
  ["title" => "History Exam #5", "content" => "Study World War II topics for the upcoming history exam. (Round 5)"],
  ["title" => "Group Meeting #5", "content" => "Don't forget the group project meeting on Tuesday at 3 PM. (Round 5)"],
  ["title" => "Submit Assignment #5", "content" => "Upload your physics assignment by Friday evening. (Round 5)"],
  ["title" => "Presentation Practice #5", "content" => "Rehearse your slides for Friday's presentation. (Round 5)"],
  ["title" => "Read a Chapter #5", "content" => "Finish reading Chapter 5 of your psychology textbook. (Round 5)"],
  ["title" => "Quiz Reminder #5", "content" => "Prepare for the biology quiz on photosynthesis. (Round 5)"],
  ["title" => "Essay Planning #5", "content" => "Outline your essay on climate change today. (Round 5)"],
  ["title" => "Flashcard Review #5", "content" => "Go through the flashcards made for chemistry. (Round 5)"],
  ["title" => "Organize Desk #5", "content" => "Clean and arrange your study space for better focus. (Round 5)"],
  ["title" => "Focus Session #5", "content" => "Try a 25-minute Pomodoro session with full concentration. (Round 5)"],
  ["title" => "Take a Break #5", "content" => "Stretch, hydrate and relax for 10 minutes. (Round 5)"],
  ["title" => "Daily Plan #5", "content" => "Make a to-do list for today’s tasks. (Round 5)"],
  ["title" => "Weekly Goals #5", "content" => "List 3 goals to complete this week. (Round 5)"],
  ["title" => "Digital Declutter #5", "content" => "Sort out your computer desktop files. (Round 5)"],
  ["title" => "Motivation Boost #5", "content" => "Remember: small progress is still progress. (Round 5)"],
  ["title" => "Catch Up #5", "content" => "Revisit lessons or materials you missed. (Round 5)"],
  ["title" => "Practice Questions #5", "content" => "Solve 5 sample problems from your workbook. (Round 5)"],
  ["title" => "Time to Reflect #5", "content" => "Write 3 sentences about what you learned today. (Round 5)"],
  ["title" => "Stay Consistent #5", "content" => "Even 10 minutes a day helps—keep showing up! (Round 5)"]
]);
?>
